name: Deploy template

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/*
      
permissions:
      id-token: write
      contents: read
env: 
  BICEP_PROJECT_PATH: '${{ github.workspace }}'
  BICEP_TEMPLATE: 'main.bicep'
  DEPLOY_LOCATION: 'northeurope'
  RESOURCEGROUP_NAME: 'Recipe06-07-rg'
  DEPLOYMENT_NAME: ${{ github.run_id }}
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCEGROUP_NAME }} \
            --template-file ${{ env.BICEP_TEMPLATE }} \
            --name ${{ env.DEPLOYMENT_NAME }}